// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrxSd06U0Jdb3Jei8smGpQ42ecA29d184',
    appId: '1:975573768996:web:23ebe495d16dc06d2f71b1',
    messagingSenderId: '975573768996',
    projectId: 'videotranslateweb',
    authDomain: 'videotranslateweb.firebaseapp.com',
    storageBucket: 'videotranslateweb.appspot.com',
    measurementId: 'G-B005LT6Q43',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiw585XhMTLtumN3xHk2LByn5MDjaNaDo',
    appId: '1:975573768996:android:e0b4501bf7b5a3832f71b1',
    messagingSenderId: '975573768996',
    projectId: 'videotranslateweb',
    storageBucket: 'videotranslateweb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB28PQAAVQPt44tcIas0EY7gTxb62kmap8',
    appId: '1:975573768996:ios:1823d11eae757c142f71b1',
    messagingSenderId: '975573768996',
    projectId: 'videotranslateweb',
    storageBucket: 'videotranslateweb.appspot.com',
    iosClientId: '975573768996-vdb5q75g2gfg2n79p8br9ao8sdfm2k4f.apps.googleusercontent.com',
    iosBundleId: 'com.kelaxa.videoweb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB28PQAAVQPt44tcIas0EY7gTxb62kmap8',
    appId: '1:975573768996:ios:1823d11eae757c142f71b1',
    messagingSenderId: '975573768996',
    projectId: 'videotranslateweb',
    storageBucket: 'videotranslateweb.appspot.com',
    iosClientId: '975573768996-vdb5q75g2gfg2n79p8br9ao8sdfm2k4f.apps.googleusercontent.com',
    iosBundleId: 'com.kelaxa.videoweb',
  );
}
